---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: exercise1
  labels:
    app: exercise1
spec:
  minReadySeconds: 3
  replicas: 3
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
        - name: incoma
          image: alpine
